const c=document.getElementById('stage');const gl=c.getContext('webgl',{antialias:false,alpha:false,preserveDrawingBuffer:false});if(!gl){document.body.innerHTML='<div style="padding:30px;color:white">WebGL required</div>';throw 0}
const V='attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';
const F=`precision highp float;uniform vec2 r,m;uniform float t,push;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+17.1;a*=.5;}return v;}
float box(vec2 p,vec2 b,float rad){vec2 q=abs(p)-b+rad;return length(max(q,0.))+min(max(q.x,q.y),0.)-rad;}
float one(vec2 p){float stem=box(p-vec2(.02,0.),vec2(.105,.57),.055);float cap=box(p-vec2(-.10,.46),vec2(.20,.10),.05);return min(stem,cap);}
float seven(vec2 p){float top=box(p-vec2(0,.49),vec2(.31,.095),.05);vec2 a=vec2(cos(-.18),-sin(-.18)),b=vec2(sin(-.18),cos(-.18));vec2 q=mat2(a,b)*vec2(p.x+.02,p.y-.02);float leg=box(q-vec2(.10,-.05),vec2(.105,.53),.05);return min(top,leg);}
float logo(vec2 p){float d=min(one(p+vec2(.66,0.)),one(p+vec2(.18,0.)));d=min(d,seven(p-vec2(.47,0.)));return d;}
void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/min(r.x,r.y);vec2 mm=(m-.5)*vec2(r.x/r.y,1.);float time=t*.35;float n=fbm(uv*2.6+vec2(time,-time*.7));float n2=fbm(uv*5.2-vec2(time*.4,time));vec2 q=uv+vec2(n-.5,n2-.5)*.075;float md=length(q-mm);q+=(q-mm)/(md+.12)*exp(-md*5.)*push*.16;float d=logo(q);d+=((n-.5)*.055+(n2-.5)*.025);float body=1.-smoothstep(-.015,.025,d);float rim=1.-smoothstep(.0,.075,abs(d));vec2 e=vec2(.006,0);float dx=logo(q+e)-logo(q-e),dy=logo(q+e.yx)-logo(q-e.yx);vec3 N=normalize(vec3(-dx*35.,-dy*35.,1.));vec3 L=normalize(vec3(-.55,.75,.7));float dif=max(dot(N,L),0.);float spec=pow(max(dot(reflect(-L,N),vec3(0,0,1)),0.),28.);float fres=pow(1.-max(N.z,0.),2.);vec3 metal=vec3(.035)+dif*vec3(.17,.19,.20)+spec*vec3(1.1)+fres*.22;float veins=smoothstep(.58,.76,fbm(q*8.+t*.12))*body;metal+=veins*vec3(.09,.11,.12);vec3 col=mix(vec3(.012),metal,body);col+=rim*body*.035;float glow=exp(-max(d,0.)*18.)*.06;col+=vec3(glow);float grain=(hash(gl_FragCoord.xy+fract(t)*91.)-.5)*.025;col+=grain;col*=.82+.18*smoothstep(1.2,.15,length(uv));gl_FragColor=vec4(pow(col,vec3(.86)),1.);}`;
function sh(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))console.log(gl.getShaderInfoLog(s));return s}let pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,V));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,F));gl.linkProgram(pr);gl.useProgram(pr);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);let a=gl.getAttribLocation(pr,'p');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);let ur=gl.getUniformLocation(pr,'r'),um=gl.getUniformLocation(pr,'m'),ut=gl.getUniformLocation(pr,'t'),up=gl.getUniformLocation(pr,'push');let mx=.5,my=.5,tx=.5,ty=.5,k=0;
function resize(){let d=Math.min(devicePixelRatio||1,1.6);c.width=innerWidth*d;c.height=innerHeight*d;gl.viewport(0,0,c.width,c.height)}function pt(e){let x=e.touches?e.touches[0].clientX:e.clientX,y=e.touches?e.touches[0].clientY:e.clientY;tx=x/innerWidth;ty=1-y/innerHeight;k=1}addEventListener('mousemove',pt);addEventListener('touchstart',pt,{passive:true});addEventListener('touchmove',pt,{passive:true});addEventListener('pointerdown',()=>k=1);addEventListener('resize',resize);resize();let st=performance.now();function draw(){mx+=(tx-mx)*.06;my+=(ty-my)*.06;k*=.965;gl.uniform2f(ur,c.width,c.height);gl.uniform2f(um,mx,my);gl.uniform1f(ut,(performance.now()-st)/1000);gl.uniform1f(up,k);gl.drawArrays(gl.TRIANGLES,0,3);requestAnimationFrame(draw)}draw();