import * as THREE from 'three';import {MarchingCubes} from 'three/addons/objects/MarchingCubes.js';import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const host=document.querySelector('#stage'),R=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});R.setPixelRatio(Math.min(devicePixelRatio,1.5));R.setSize(innerWidth,innerHeight);R.shadowMap.enabled=true;R.toneMapping=THREE.ACESFilmicToneMapping;R.toneMappingExposure=1.15;host.appendChild(R.domElement);
const S=new THREE.Scene();S.background=new THREE.Color(0xdfb29f);const C=new THREE.PerspectiveCamera(32,innerWidth/innerHeight,.1,30);C.position.set(0,0,6.4);
const M=new THREE.MeshPhysicalMaterial({color:0xd99582,roughness:.38,metalness:0,clearcoat:.62,clearcoatRoughness:.32,sheen:1,sheenColor:new THREE.Color(0xffc8bb),sheenRoughness:.55,subsurface:true});
const body=new MarchingCubes(innerWidth<700?46:56,M,true,true,160000);body.scale.set(3.1,3.1,.9);body.position.y=-.02;S.add(body);
S.add(new THREE.HemisphereLight(0xffe6dc,0x6b3a34,2.3));let key=new THREE.DirectionalLight(0xfff0e8,4.5);key.position.set(-3,4,5);S.add(key);let fill=new THREE.PointLight(0xff9f91,18,10);fill.position.set(3,-1,4);S.add(fill);
const comp=new EffectComposer(R);comp.addPass(new RenderPass(S,C));comp.addPass(new OutputPass());
let mouse=new THREE.Vector2(.5,.5),target=mouse.clone(),force=0,targetForce=0,clock=new THREE.Clock();
const B=(x,y,z,s,str=11)=>body.addBall(x,y,z,s,str);
function one(cx,t,squish){for(let i=0;i<11;i++){let y=.20+i*.052;B(cx+Math.sin(t*1.2+i*.7)*.006,y,.50,.36+squish*.04,12)}for(let i=0;i<5;i++)B(cx-.055+i*.012,.72-i*.006,.50,.34,12);B(cx,.17,.5,.39,12)}
function seven(cx,t,squish){for(let i=0;i<10;i++)B(cx-.13+i*.029,.72,.5,.35+squish*.025,12);for(let i=0;i<11;i++){let u=i/10;B(cx+.105-u*.13,.68-u*.50,.5,.36+squish*.035,12)}B(cx-.035,.18,.5,.39,12)}
function faceDetails(){body.addPlaneX(2.4,12);body.addPlaneY(2.4,12)}
function rebuild(t){body.reset();let pulse=.5+.5*Math.sin(t*1.45),sq=force*(.6+.4*Math.sin(t*3));one(.285,t,sq);one(.455,t+.7,sq);seven(.665,t+1.2,sq);let px=.5+(mouse.x-.5)*.42,py=.5+(mouse.y-.5)*.55;if(force>.02){body.addBall(px,py,.46,.18+force*.12,15);body.addBall(px+.025,py-.02,.48,.14+force*.08,16)}faceDetails();body.update()}
function point(e){let q=e.touches?e.touches[0]:e;target.set(q.clientX/innerWidth,1-q.clientY/innerHeight);targetForce=1}addEventListener('pointerdown',point);addEventListener('pointermove',e=>{if(e.buttons)point(e)});addEventListener('pointerup',()=>targetForce=0);addEventListener('touchstart',point,{passive:true});addEventListener('touchmove',point,{passive:true});addEventListener('touchend',()=>targetForce=0,{passive:true});
function loop(){requestAnimationFrame(loop);let t=clock.getElapsedTime();mouse.lerp(target,.09);force+=(targetForce-force)*.08;if(!targetForce)force*=.94;rebuild(t);body.rotation.y=(mouse.x-.5)*.16+Math.sin(t*.25)*.035;body.rotation.x=-(mouse.y-.5)*.08+Math.sin(t*.31)*.018;body.scale.z=.88+.05*Math.sin(t*1.1);key.position.x=-3+Math.sin(t*.45);comp.render()}function resize(){C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight);comp.setSize(innerWidth,innerHeight)}addEventListener('resize',resize);resize();loop();